server:
  port: 9003
spring:
  application:
    name: wishlist_service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
