server:
  port: 9004
spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.80.38:8765/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: comment
    ip-address: 192.168.80.11

